# Form implementation generated from reading ui file '.\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from qfluentwidgets import (
    BodyLabel,
    CheckBox,
    FluentIcon,
    HyperlinkButton,
    LineEdit,
    PrimaryPushButton,
    RadioButton,
    SmoothScrollArea,
    TransparentPushButton,
)


class ImageLabel(QtWidgets.QLabel):
    def __init__(self, image_path, parent=None):
        super().__init__(parent)
        self.image_path = image_path
        self.setScaledContents(False)

    def paintEvent(self, event):
        painter = QtGui.QPainter(self)
        pixmap = QtGui.QPixmap(self.image_path)
        if pixmap.isNull():
            return

        # Scale keeping aspect ratio by expanding (cover)
        scaled = pixmap.scaled(
            self.size(),
            QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
            QtCore.Qt.TransformationMode.SmoothTransformation,
        )

        # Center the image
        x = (self.width() - scaled.width()) // 2
        y = (self.height() - scaled.height()) // 2

        painter.drawPixmap(x, y, scaled)


class Ui_Form:
    login_button_clicked = pyqtSignal()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 1000)
        Form.setMinimumSize(QtCore.QSize(1200, 500))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)

        # Left banner image
        self.label = ImageLabel(":/resource/images/gd3u3ibyyp.jpg", parent=Form)
        self.label.setSizePolicy(
            QtWidgets.QSizePolicy(
                QtWidgets.QSizePolicy.Policy.Expanding,
                QtWidgets.QSizePolicy.Policy.Preferred,
            )
        )
        self.horizontalLayout.addWidget(self.label)

        # Right container
        self.right_big_widget = QtWidgets.QWidget(parent=Form)
        self.right_big_widget.setObjectName("right_big_widget")
        self.right_big_widget.setStyleSheet(
            "#right_big_widget { background-color: white; }"
        )
        self.right_big_widget.setSizePolicy(
            QtWidgets.QSizePolicy(
                QtWidgets.QSizePolicy.Policy.Expanding,
                QtWidgets.QSizePolicy.Policy.Preferred,
            )
        )
        self.right_big_vlayout = QtWidgets.QVBoxLayout(self.right_big_widget)
        self.right_big_vlayout.setContentsMargins(20, 20, 20, 20)
        self.right_big_vlayout.setSpacing(12)

        # Scrollable form area
        self.scrollArea = SmoothScrollArea(parent=self.right_big_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setStyleSheet("background: transparent; border: none;")
        self.scrollArea.setSizePolicy(
            QtWidgets.QSizePolicy(
                QtWidgets.QSizePolicy.Policy.Expanding,
                QtWidgets.QSizePolicy.Policy.Expanding,
            )
        )
        self.scrollArea.setMinimumWidth(380)
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setStyleSheet("background: transparent;")
        self.formLayout = QtWidgets.QVBoxLayout(self.scrollContent)
        self.formLayout.setContentsMargins(12, 36, 12, 16)
        self.formLayout.setSpacing(16)
        self.top_spacer = QtWidgets.QSpacerItem(
            20,
            120,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        # ISP on top (no label text)
        self.isp_layout = QtWidgets.QHBoxLayout()
        self.isp_cmcc_rbtn = RadioButton("移动")
        self.isp_unicom_rbtn = RadioButton("联通")
        self.isp_telecom_rbtn = RadioButton("电信")
        self.isp_layout.addWidget(self.isp_cmcc_rbtn)
        self.isp_layout.addWidget(self.isp_unicom_rbtn)
        self.isp_layout.addWidget(self.isp_telecom_rbtn)
        self.isp_cmcc_rbtn.setChecked(True)
        # ISP button group
        self.isp_btn_group = QtWidgets.QButtonGroup(self)
        self.isp_btn_group.addButton(self.isp_cmcc_rbtn)
        self.isp_btn_group.addButton(self.isp_unicom_rbtn)
        self.isp_btn_group.addButton(self.isp_telecom_rbtn)

        # Basic fields
        self.username_label = BodyLabel("用户名")
        self.username_edit = LineEdit()
        self.username_edit.setClearButtonEnabled(True)
        self.username_edit.setPlaceholderText("统一认证号")

        self.password_label = BodyLabel("密码")
        self.password_edit = LineEdit()
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setClearButtonEnabled(True)

        # Remember Password and Auto Login
        self.checkbox_layout = QtWidgets.QHBoxLayout()
        self.remember_cb = CheckBox("记住密码")
        self.auto_login_cb = CheckBox("自动登录")
        self.checkbox_layout.addWidget(self.remember_cb)
        self.checkbox_layout.addSpacing(20)
        self.checkbox_layout.addWidget(self.auto_login_cb)
        self.checkbox_layout.addStretch(1)

        # Advanced section toggle (collapsible arrow)
        self.advanced_toggle_btn = TransparentPushButton(parent=self)
        self.advanced_toggle_btn.setText("高级设置")
        self.advanced_toggle_btn.setIcon(FluentIcon.CHEVRON_RIGHT_MED)
        self.advanced_toggle_btn.setCheckable(True)
        self.advanced_toggle_btn.setChecked(False)
        self.advanced_toggle_btn.setIconSize(QtCore.QSize(12, 12))
        self.advanced_toggle_btn.toggled.connect(self._toggle_advanced_section)

        # Advanced content
        self.advanced_widget = QtWidgets.QWidget()
        self.advanced_layout = QtWidgets.QVBoxLayout(self.advanced_widget)
        self.advanced_layout.setContentsMargins(0, 0, 0, 0)
        self.advanced_layout.setSpacing(8)

        # IP option (radio: local vs other)
        self.ip_title = BodyLabel("IP 设置")
        self.ip_method_layout = QtWidgets.QHBoxLayout()
        self.use_local_ip_rbtn = RadioButton("使用本机 IP")
        self.use_other_ip_rbtn = RadioButton("使用其他设备 IP")
        self.use_local_ip_rbtn.setChecked(True)
        self.ip_method_layout.addWidget(self.use_local_ip_rbtn)
        self.ip_method_layout.addWidget(self.use_other_ip_rbtn)
        # IP method button group
        self.ip_method_btn_group = QtWidgets.QButtonGroup(self)
        self.ip_method_btn_group.addButton(self.use_local_ip_rbtn)
        self.ip_method_btn_group.addButton(self.use_other_ip_rbtn)
        self.use_local_ip_rbtn.toggled.connect(self._toggle_ip_input)
        self.use_other_ip_rbtn.toggled.connect(self._toggle_ip_input)
        self.other_ip_edit = LineEdit()
        self.other_ip_edit.setClearButtonEnabled(True)
        self.other_ip_edit.setPlaceholderText("此处填写其他设备 IPv4 地址")
        self.other_ip_edit.setVisible(False)

        # Device role
        self.device_label = BodyLabel("登录端类型")
        self.device_layout = QtWidgets.QHBoxLayout()
        self.device_pc_rbtn = RadioButton("作为电脑端登录")
        self.device_pe_rbtn = RadioButton("作为移动端登录")
        self.device_pe_rbtn.setChecked(True)
        self.device_layout.addWidget(self.device_pc_rbtn)
        self.device_layout.addWidget(self.device_pe_rbtn)
        # Device button group
        self.device_btn_group = QtWidgets.QButtonGroup(self)
        self.device_btn_group.addButton(self.device_pc_rbtn)
        self.device_btn_group.addButton(self.device_pe_rbtn)

        # Login type
        self.login_type_label = BodyLabel("登录方式")
        self.login_type_layout = QtWidgets.QHBoxLayout()
        self.login_type_normal_rbtn = RadioButton("普通登录")
        self.login_type_special_rbtn = RadioButton("特殊登录(已失效)")
        self.login_type_normal_rbtn.setChecked(True)
        self.login_type_layout.addWidget(self.login_type_normal_rbtn)
        self.login_type_layout.addWidget(self.login_type_special_rbtn)
        # Login type button group
        self.login_type_btn_group = QtWidgets.QButtonGroup(self)
        self.login_type_btn_group.addButton(self.login_type_normal_rbtn)
        self.login_type_btn_group.addButton(self.login_type_special_rbtn)

        # Build advanced layout
        self.advanced_layout.addWidget(self.ip_title)
        self.advanced_layout.addLayout(self.ip_method_layout)
        self.advanced_layout.addWidget(self.other_ip_edit)
        self.advanced_layout.addWidget(self.device_label)
        self.advanced_layout.addLayout(self.device_layout)
        self.advanced_layout.addWidget(self.login_type_label)
        self.advanced_layout.addLayout(self.login_type_layout)
        self.advanced_widget.setVisible(False)

        # Self-service link
        self.self_service_btn = HyperlinkButton()
        self.self_service_btn.setText("自服务")

        # Login button
        self.loginButton = PrimaryPushButton(text="登录", parent=self.right_big_widget)
        self.loginButton.clicked.connect(self.login_button_clicked)

        # Assemble form
        self.formLayout.addSpacerItem(self.top_spacer)
        self.formLayout.addLayout(self.isp_layout)
        self.formLayout.addSpacing(6)
        self.formLayout.addWidget(self.username_label)
        self.formLayout.addWidget(self.username_edit)
        self.formLayout.addWidget(self.password_label)
        self.formLayout.addWidget(self.password_edit)
        self.formLayout.addLayout(self.checkbox_layout)
        self.formLayout.addWidget(
            self.advanced_toggle_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.formLayout.addSpacing(4)
        self.formLayout.addWidget(self.advanced_widget)
        self.formLayout.addWidget(self.self_service_btn)
        self.formLayout.addStretch()

        self.scrollArea.setWidget(self.scrollContent)
        self.right_big_vlayout.addWidget(self.scrollArea)
        self.right_big_vlayout.addWidget(self.loginButton)

        self.horizontalLayout.addWidget(self.right_big_widget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        Form.setLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def _toggle_advanced_section(self, checked: bool):
        self.advanced_widget.setVisible(checked)
        self.advanced_toggle_btn.setIcon(
            FluentIcon.CHEVRON_DOWN_MED if checked else FluentIcon.CHEVRON_RIGHT_MED
        )

    def _toggle_ip_input(self):
        show_other = self.use_other_ip_rbtn.isChecked()
        self.other_ip_edit.setVisible(show_other)
        if not show_other:
            self.other_ip_edit.clear()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
